# Generated by Django 4.0.3 on 2022-03-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_familiar_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='hobby',
            field=models.CharField(default='Pelotita', max_length=30),
        ),
    ]
